import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import Header from "./header.js";
import SearchRoundedIcon from "@material-ui/icons/SearchRounded";
import FilterSection from "../component/FilterSection.js";
import DataSetDisplay from "../component/DisplayDataset";
import axios from "axios";
import server, { option } from "../main_config";
import { resolveHref } from "next/dist/next-server/lib/router/router";
import ArrowBackIosIcon from '@material-ui/icons/ArrowBackIos';
import ArrowForwardIosIcon from '@material-ui/icons/ArrowForwardIos';
export interface HomeState {
  List?: {
    img: string;
    format: string;
    name: string;
    num: number;
    size: number;
    tags: string[];
    _id: string;
    category: string;
    create_time: string;
    department: string;
  }[];
  pages:[];
  pagesIndex:number;
  data: { title: string; arr: string[] }[];
}
// class MyComponent<P, S> extends <P, HomeState & S> {}
export default class Home extends React.Component<{}, HomeState> {
  constructor(props) {
    super(props);
    this.state = {
      List:[],
      pages:[],
      pagesIndex:1,
      valueName:"",
      childrenMsg:"",
      tags:"",
      tasks:"",
      data: [{ 
        title:"标注类型",
        arr: ['4','5'], 
      },
      { 
        title:"数据格式",
        arr: ['4','5'], 
      },],
    }
  }

  handleKeyDown = (e) => {
    console.log(1)
    if (e.keyCode === 13) {
        console.log("按下了Enter键");
        this.grid(1)
    }
  }
  getChildrenMsg = (result, msg,ind) => {
    // console.log(result, msg)
    // 很奇怪这里的result就是子组件那bind的第一个参数this，msg是第二个参数
    var ms=["",""];
    ms[ind]=msg;
      if(ind === 0 ){
        this.setState({
          tags:msg
        })
      } else {
        this.setState({
          tasks:msg
        })
      }
      this.grid(1,ms[0],ms[1])
    }
  callback(msg){
      console.log(msg);
  }

  grid = (value,tags,tasks) => {  //展开文章内容
    var tag = tags? tags : this.state.tags
    var tas = tasks ? tasks : this.state.tasks
    axios 
      .get(`${server}${option.dataset}`+"?limit=18&page="+ value+"&keywords="+this.state.valueName+"&tags="+tag+"&tasks="+tas)
      .then((res) => {
        if (
          res.status === 200 &&
          !(console.log(`${server}${option.dataset}`), 0)
        ) {
          this.setState({ List: res.data.data });
          console.log(res.data);
          var count=parseInt(res.data.count/15+1);
          var numb = []
          for(let i=1;i<=count;i++){
            numb.push(i)
          }
          this.setState({
            pages:numb
          })
          
        } else {
          console.log(`${server}${option.dataset} mulfunctioning`);
        }
      })
      .catch(function (error) {
        console.log(error);
      });
  }
  componentDidMount() {
    
    this.grid(1)
    // localStorage.setItem("phone", "123")
    // //对象
    // let user = JSON.parse(localStorage.getItem("username"))
    const homebox = document.querySelector('#homebox');
    const header_ = document.querySelector('#header_');
    let Observe_options = {
      root:null,
      rootMargin:"0px",
      threshold:[0.9,0.89,0.88,0.8,0.7,0.5,0]
    }
    let callback = (entries, observer) =>{
      console.log(entries)
      entries.forEach(entry =>{
        console.log(entry)
        if (entry.intersectionRatio < 1) document.querySelector('#header_>div:nth-of-type(1)').style.backgroundColor = 'black'
      })
     
    }

    let observer = new IntersectionObserver(callback, Observe_options);
    observer.observe(homebox)

    axios.get(server + 'get_dataset_info',{})

        .then((response) => {
          
          response.data.data
          var setdata=this.state.data;
          setdata[0].arr=response.data.data.tags
          setdata[1].arr=response.data.data.tasks
          this.setState({
            data:setdata
          })
        })
        .catch(function (error) {
            console.log(error);
        });
  }

  render() {
    // localStorage.setItem("phone", "123")
    //对象
    // let user = JSON.parse(localStorage.getItem("phone"))
    // console.log(user)
    return (
      <div>
        <Head>
          <title>数据集平台</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logov.png" />
        </Head>
        <Header />
        <div className={styles.homeBox} id = "homebox">
          {/* <div className={styles.img} style={{backgroundImage: "url(" + ("/bjt.png") + ")"}}> */}
          <div className={styles.img}>
            <Image
              src="/bj-left.png"
              className={styles.imgleft}
              alt="Fawai Logo"
              width={439}
              height={424}
            />
            <div className={styles.imgright}>
              <Image
                src="/bj-right.png"
                alt="Fawai Logo"
                width={478}
                height={424}
              />
            </div>
          </div>
          <div className={styles.homeTitle}>公开数据集</div>
          <div className={styles.searchBox}>
            <div className={styles.searchHome}>
              <div className={styles.searchLeft}>
                <SearchRoundedIcon style={{ fontSize: 26, marginTop: 15 }} />
                <input
                  type="text"
                  value={this.state.valueName}
                  onKeyDown={(e)=>this.handleKeyDown(e)}
                  onChange={(e) => {
                    this.setState({
                      valueName:e.target.value
                    })
                  }}
                  className={styles.searchInput}
                  placeholder="搜索数据集关键字"
                />
              </div>
              <div className={styles.searchRight}>
                <span className={styles.searchNumber}>{this.state.List.length}</span>
                <span>公开数据集</span>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.listHome}>
          <div className={styles.listContainer}>
            <div className={styles.filterContainer} style={{width:'278px'}}>
              <FilterSection data={this.state.data} parent={this} father={'index'} />
            </div>
            <div style={{width:"937px"}}>
              <DataSetDisplay data={this.state.List} accessibility={"public"} />
              <div className={styles.pages}>
                <div className={styles.pagesLable} onClick={() => {
                    if(this.state.pagesIndex>0){
                      this.setState({
                        pagesIndex:this.state.pagesIndex-1
                      })
                      this.grid(this.state.pagesIndex-1)
                    }
                    
                  }}>
                  <ArrowBackIosIcon style={{fontSize:12}} />
                </div>
                {this.state.pages ? this.state.pages.map((item, index) => {
                      return (
                        <div className={this.state.pagesIndex === item?styles.pagesLableStyle :styles.pagesLable}  onClick={() => {
                          this.setState({
                            pagesIndex:item
                          })
                          this.grid(item)
                        }}>{item}</div>
                  );
                }):<div className={styles.pagesLable}>1</div>}
                
                <div className={styles.pagesLable} onClick={() => {
                    if(this.state.pagesIndex<this.state.pages.length){
                      this.setState({
                        pagesIndex:this.state.pagesIndex+1
                      })
                      this.grid(this.state.pagesIndex+1)
                    }
                    
                  }}>
                  <ArrowForwardIosIcon style={{fontSize:12}} />
                </div>
              </div>
            </div>     
          </div>
        </div>
      </div>
    );
  }
}
