import Head from "next/head";
import Image from "next/image";
import React from "react";
import styles from "../styles/Home.module.css";
import Header from "./header.js";
import SearchRoundedIcon from "@material-ui/icons/SearchRounded";
import DataSetLeft from "./DataSetLeft.js";
import DataSet from "../component/Grid";
import axios from "axios";
import server, { option } from "./main_config";
import { resolveHref } from "next/dist/next-server/lib/router/router";
export interface HomeState {
  List?: {
    img: string;
    format: string;
    name: string;
    num: number;
    size: number;
    tags: string[];
    _id: string;
    category: string;
    create_time: string;
    department: string;
  }[];
  data: { title: string; arr: string[] }[];
}
// class MyComponent<P, S> extends <P, HomeState & S> {}
export default class Home extends React.Component<{}, HomeState> {
  constructor(props) {
    super(props);
    this.state = {
      List:[],
      data: [
        {
          title: "数据格式",
          arr: [
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
          ],
        },
        {
          title: "标注类型",
          arr: [
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
          ],
        },
        {
          title: "任务类型",
          arr: [
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
            "dd21",
            "124",
          ],
        },
      ],
    };
  }

  componentDidMount() {
    axios
      .get(`${server}${option.dataset}`)
      .then((res) => {
        if (
          res.status === 200 &&
          !(console.log(`${server}${option.dataset}`), 0)
        ) {
          this.setState({ List: res.data.data });
          console.log(res.data.data);
        } else {
          console.log(`${server}${option.dataset} mulfunctioning`);
        }
      })
      .catch(function (error) {
        console.log(error);
      });
    // localStorage.setItem("phone", "123")
    // //对象
    // let user = JSON.parse(localStorage.getItem("username"))
    const homebox = document.querySelector('#homebox');
    const header_ = document.querySelector('#header_');
    let Observe_options = {
      root:null,
      rootMargin:"0px",
      threshold:[0.9,0.89,0.88,0.8,0.7,0.5,0]
    }
    let callback = (entries, observer) =>{
      entries.forEach(entry =>{
        console.log(entry)
        if (entry.intersectionRatio < 1) document.querySelector('#header_>div:nth-of-type(1)').style.backgroundColor = 'black'
      })
     
    }

    let observer = new IntersectionObserver(callback, Observe_options);
    observer.observe(homebox)
  }

  render() {
    // localStorage.setItem("phone", "123")
    //对象
    // let user = JSON.parse(localStorage.getItem("phone"))
    // console.log(user)
    return (
      <div>
        <Head>
          <title>数据集平台</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logov.png" />
        </Head>
        <Header />
        <div className={styles.homeBox} id = "homebox">
          {/* <div className={styles.img} style={{backgroundImage: "url(" + ("/bjt.png") + ")"}}> */}
          <div className={styles.img}>
            <Image
              src="/bj-left.png"
              className={styles.imgleft}
              alt="Fawai Logo"
              width={439}
              height={424}
            />
            <div className={styles.imgright}>
              <Image
                src="/bj-right.png"
                alt="Fawai Logo"
                width={478}
                height={424}
              />
            </div>
          </div>
          <div className={styles.homeTitle}>公开数据集</div>
          <div className={styles.searchBox}>
            <div className={styles.searchHome}>
              <div className={styles.searchLeft}>
                <SearchRoundedIcon style={{ fontSize: 26, marginTop: 15 }} />
                <input
                  type="text"
                  className={styles.searchInput}
                  placeholder="搜索数据集关键字"
                />
              </div>
              <div className={styles.searchRight}>
                <span className={styles.searchNumber}>3723</span>
                <span>公开数据集</span>
              </div>
            </div>
          </div>
        </div>
        <div className={styles.listHome}>
          <div className={styles.listContainer}>
            <div className={styles.filterContainer}>
              <DataSetLeft data={this.state.data} />
            </div>
            <DataSet data={this.state.List} accessibility={"public"} />
          </div>
        </div>
      </div>
    );
  }
}
